[package]
name = "nn"
version = "0.0.0"
authors = ["Jorge Aparicio <japaricious@gmail.com>"]

[dependencies]
byteorder = "*"
image = "*"
rand = "*"
time = "*"

[dependencies.cast]
git = "https://github.com/japaric/cast.rs"

[dependencies.linalg]
git = "https://github.com/japaric/linalg.rs"
